### ISSUE TITLE
Ending single quot is a part of a URL

### ISSUE THREAD

**Issue by isaranchuk** [gregjacobs/Autolinker.js#113] opened 2015-07-02 10:13 UTC
Hi.
I've just spotted an issue that result of autolinking of 'http://test' will be:
<i>'<a href="http://test'">http://test'</a></i>
So the ending  <b>single</b> quot is a part of an URL, which is not correct.
But at the same time it is not a case for <b>double</b> quot.

Maybe, the issue is that single quot is not included into <i>htmlCharacterEntitiesRegex</i>?
(can relate to https://github.com/gregjacobs/Autolinker.js/pull/105)

**Comment by gregjacobs** [comment] 2015-11-11 04:33
Hmm, so single quotes are valid in a URL, but if the character before the URL is also a single quote, I think we should ignore it. We do this with parenthesis right now as well. Will look into this.

**Comment by olafleur** [comment] 2017-03-03 02:46
Could not reproduce in 1.4.2 . Closing.

**Closed by olafleur** 2017-03-03 02:46 UTC
Labels: bug
