### ISSUE TITLE
Add URL prefix on demand

### ISSUE THREAD

**Issue by isaranchuk** [gregjacobs/Autolinker.js#114] opened 2015-07-02 10:24 UTC
Hi.
Currently when we disable URL stripping (stripUrl=false), we will have the following:
google.com => http://google.com

Is it possible some how to don't show prefix if it wasn't specified manually?
Thanks.

**Comment by philfreo** [comment] 2015-08-10 22:58
I think this is a dupe of #73

**Comment by gregjacobs** [comment] 2015-11-08 21:19
Fixed in v0.21.0

**Closed by gregjacobs** 2015-11-08 21:19 UTC
